cp -v ~/.bashrc .
cp -v ~/.vimrc* ./vim/
cp -v ~/.vim/colors/monokk.vim ./vim/
cp -v ~/.vim/syntax/python.vim ./vim/
cp -v ~/.vim/after/plugin/ms.vim ./vim/
cp -v ~/lemon.sh ./lemonbar/ 
cp -v ~/.gitconfig ./git/
cp -v ~/git-prompt.sh ./git/
cp -v ~/.config/fish/config.fish ./fish/ 
cp -v ~/.config/fish/functions/fish_prompt.fish ./fish/ 
cp -v ~/.config/bspwm/bspwmrc ./bspwm/ 
cp -v ~/.config/sxhkd/sxhkdrc ./bspwm/ 
