#! /bin/sh

sxhkd &

xrandr --output VGA1 --primary 
xrandr --output HDMI2 --right-of VGA1

bspc monitor VGA1 -d 1 2 3
bspc monitor HDMI2 -d 4 5 6


bspc config border_width         0
bspc config window_gap          40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/Descargas/back.jpg

Escritorio/lemon.sh

